story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'

urlpatterns = [
    path('story1',views.story1, name='story1'),
]

story4_akbar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('profile_page.urls')),
    path('', include('story1.urls')),
    path('', include('story5.urls')),
    path('', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('',views.home7,name='home7'),
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('',views.home8b,name='home8b'),
    path('search/',views.home8,name='home8'),
]

story9/urls.py
from django.urls import path, include
from . import views

app_name = 'story9'

urlpatterns = [
    path('',views.home9,name="home9"),
    path('',include("django.contrib.auth.urls")),
    path('register',views.register9,name='register9'),
    path('logged_in',views.logged_in9,name='logged_in9'),
]

story1/models.py
from django.db import models

# Create your models here.

story1/views.py
from django.shortcuts import render

# Create your views here.
def story1(request):
    return render(request, 'story1.html')

templates/HobbiesPage.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    {% block title %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Akbar's Hobby</title>

    <link rel="icon" href="{% static 'images/Group 3.png' %}" type="image/icon type">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'CSS/style.css' %}">

    <link href="https://fonts.googleapis.com/css2?family=Rubik" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
    {% endblock %}
</head>

<body>

    {% block content %}
    <div class="container" id="judul-resume">
        <div class="judul">
            <p id="judul-resume">My Hobbies</p>
        </div>
    </div>

    <div class="container" id="hobi">
        <div class="isi-hobi">
            <div class="hobi-1">
                <div class="row">
                    <div class="col-xl-4">
                        <img src="{% static 'images/Group 10.png' %}" alt="" id="foto-badminton">
                    </div>

                    <div class="col-xl-2"></div>

                    <div class="col-xl-6" id="artikel-hobi">
                        <div class="row">
                            <p id="judul-hobi">
                                Badminton
                            </p>
                        </div>

                        <div class="row">
                            <p id="konten-hobi">
                                I love to play badminton since i was at Elementary. Since then, i always play badminton with my friend after school finished.
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="hobi-2">
                <div class="row">
                    <div class="col-xl-1"></div>

                    <div class="col-xl-6" id="artikel-hobi">
                        <div class="row">
                            <p id="judul-hobi">
                                Volleyball
                            </p>
                        </div>

                        <div class="row">
                            <p id="konten-hobi">
                                My first play of volleyball game was at Highschool. Me and my friend always enjoyed the play that we had. Volleyball is  fun !
                            </p>
                        </div>
                    </div>

                    <div class="col-xl-4">
                        <img src="{% static 'images/Group 11.png' %}" alt="" id="foto-voli">
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

</body>
</html>

templates/LandingPage.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    {% block title %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Akbar's profile</title>

    <link rel="icon" href="{% static 'images/Group 3.png' %}" type="image/icon type">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'CSS/style.css' %}">

    <link href="https://fonts.googleapis.com/css2?family=Rubik" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
    {% endblock %}
</head>

<body>
    {% block content %}

    <div class="container" id="konten-atas">
        <div class="row">
            <div class="col-xl">
                <div class="atas-kiri">
                    <img src="{% static 'images/Group 4.png' %}" alt="orang-ganteng" width="100%" max-width="500px" height="auto">
                </div>
            </div>
    
            <div class="col-xl">
                <div class="row-xl" id="atas-kanan-atas">
                    <div class="text-perkenalan">
                        <p id="hello">Hello !</p>
                        <p id="my-name">My name is</p>
                        <p id="nama">AKBAR</p>
                        <p id="jurusan">Information System Student</p>
                    </div>
                </div>

                <div class="row-xl" id=bawah-kanan-atas>
                    <div class="tombol-content">
                        <a href="projects"><img src="{% static 'images/Group 5.png' %}" alt="" id="projects"></a>
                        <a href="resume"><img src="{% static 'images/Group 6.png' %}" alt="" id="resume"></a>
                        <a href="hobbies"><img src="{% static 'images/Group 7.png' %}" alt="" id="hobbies"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container" id="konten-bawah">
        <div class="about-me">
            <p id="about-me-judul">About me</p>
            <p id="about-me-isi">I’m a student majoring Information System at Universitas Indonesia. I study about tech, business, and management. I understand several programming language. If you want to know more information about me please comfort yourself to click one of the circle above</p>
        </div>
    </div>


    {% endblock %}
</body>
</html>

templates/NewPage.html
<!DOCTYPE html>
{% extends 'base1page.html' %}
{% load static %}
<html lang="en">
<head>
    {% block title %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bonus Page</title>

    <link rel="icon" href="{% static 'images/Group 3.png' %}" type="image/icon type">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'CSS/style.css' %}">

    <link href="https://fonts.googleapis.com/css2?family=Rubik" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
    <style>
        body{
            background-image: url('../static/images/bonuspage_background2.jpg');
        }
    </style>
    {% endblock %}
</head>

<body>
    {% block content %}

    <div class="container" id="konten-project">
        <div class="kotak-biru">
            <p id="no-project">Coming Soon.</p>
        </div>
    </div>

    {% endblock %}
</body>
</html>

templates/ProjectPage.html
<!DOCTYPE html>
{% extends 'base1page.html' %}
{% load static %}
<html lang="en">
<head>
    {% block title %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Akbar's Project</title>

    <link rel="icon" href="{% static 'images/Group 3.png' %}" type="image/icon type">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'CSS/style.css' %}">

    <link href="https://fonts.googleapis.com/css2?family=Rubik" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
    {% endblock %}
</head>

<body>
    {% block content %}

    <div class="container" id="konten-project">
        <div class="kotak-biru">
            <p id="no-project">No projects yet</p>
        </div>
    </div>

    {% endblock %}
</body>
</html>

templates/ResumePage.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    {% block title %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Akbar's Resume</title>

    <link rel="icon" href="{% static 'images/Group 3.png' %}" type="image/icon type">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'CSS/style.css' %}">

    <link href="https://fonts.googleapis.com/css2?family=Rubik" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
    {% endblock %}
</head>

<body>
    {% block content %}

    <div class="container" id="judul-foto">
        <div class="judul">
            <p id="judul-resume">My Resume</p>
        </div>

        <div class="foto-resume">
            <img src="{% static 'images/Group 9.png' %}" alt="" id="foto-resume1">
        </div>
    </div>

    <div class="container" id="education">
        <div class="judul-education">
            <p id="judul-ed">Educational Background</p>
        </div>

        <div class="isi-education">
            <div class="row">
                <div class="col-xl-1"></div>
                <div class="col-xl-7">
                    <p id="UI">Universitas Indonesia (2019 - Present)</p>
                </div>

                <div class="col-xl-4">
                    <img src="{% static 'images/image 2.png' %}" alt="" id="logo-ui">
                </div>
            </div>
                
            <div class="row">
                <div class="col-xl-1"></div>
                <div class="col-xl-4">
                    <img src="{% static 'images/image 1.png' %}" alt="" id="logo-28">
                </div>

                <div class="col-xl-7">
                    <p id="UI">SMAN 28 Jakarta (2016 - 2019)</p>
                </div>
            </div>
        </div>
    </div>

    <div class="container" id="education">
        <div class="judul-education">
            <p id="judul-ed">Organization Experiences</p>
        </div>

        <div class="isi-education">
            <div class="row">
                <div class="col-xl-1"></div>
                <div class="col-xl-7">
                    <p id="UI">Pesta Rakyat Komputer (2020)</p>
                    <p id="sub-UI">Staff of Futsal Planner</p>
                </div>

                <div class="col-xl-4">
                    <img src="{% static 'images/image 3.png' %}" alt="" id="logo-perak">
                </div>
            </div>
                
            <div class="row">
                <div class="col-xl-1"></div>
                <div class="col-xl-4">
                    <img src="{% static 'images/Copy of Asset 9 1.png' %}" alt="" id="logo-compfest">
                </div>

                <div class="col-xl-7">
                    <p id="UI">COMPFEST (2020)</p>
                    <p id="sub-UI">Staff of Equipment and Security</p>
                </div>
            </div>
        </div>

        <div class="container" id="education">
            <div class="judul-education">
                <p id="judul-ed">Skills</p>
            </div>
    
            <div class="isi-education">
                <div class="row">
                    <div class="col-xl-1"></div>

                    <div class="col-xl-3">
                        <img src="{% static 'images/Python.png' %}" alt="" id="logo-python">
                    </div>

                    <div class="col-xl-3">
                        <img src="{% static 'images/Java.png' %}" alt="" id="logo-java">
                    </div>

                    <div class="col-xl-3">
                        <img src="{% static 'images/Excel.png' %}" alt="" id="logo-excel">
                    </div>

                    <div class="col-xl-1"></div>
                </div>
                    
                <div class="row" id="skill-2">
                    <div class="col-xl-1"></div>

                    <div class="col-xl-3">
                        <img src="{% static 'images/PowerPoint.png' %}" alt="" id="logo-ppt">
                    </div>

                    <div class="col-xl-3">
                        <img src="{% static 'images/Word.png' %}" alt="" id="logo-word">
                    </div>

                    <div class="col-xl-1"></div>
                </div>
            </div>
        </div>
    </div>

    {% endblock %}
</body>
</html>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

    {% block title %}
    {% endblock %}
    
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light" id="navbar">
        <div id="nav-kiri">
            <img src="{% static 'images/Group 3.png' %}" alt="orang_ganteng" width="60px" height="60px">
            <p>Muhamad Akbar Syahputra Adha</p>
        </div>

        <div id="nav-kanan">
            <ul class="nav">
                <li class="nav-item">
                    <a class="nav-link" href="/home">Home</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="#!">Story PPW <img src="{% static 'images/drop-down-arrow.png' %}" alt="dropdown arrow" width="10px" height="10px"></a>

                    <div class="dropdown-content">
                        <a href="/story1">Story 1</a>
                        <a href="/story5">Story 5</a>
                        <a href="/story6">Story 6</a>
                        <a href="{% url 'story7:home7' %}">Story 7</a>
                        <a href="{% url 'story8:home8b' %}">Story 8</a>
                        <a href="{% url 'story9:home9' %}">Story 9</a>
                        <a href="/coming-soon">Coming Soon</a>
                    </div>
                </li>
              </ul>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

    <div class="footer">
        <div class="sosmed">
            <div class="kiri">
                <a href="/home"><img src="{% static 'images/home.png' %}" alt="" id="home"></a>
            </div>
            <div class="tengah">
                <a href="https://www.youtube.com/channel/UCmxW3Ywk5kM4k9vPuPBffLg"><img src="{% static 'images/Youtube.png' %}" alt="" id="youtube"></a>
                <a href="https://www.linkedin.com/in/muhamad-akbar-syahputra-adha-99b3b9175/"><img src="{% static 'images/LinkedIN.png' %}" alt="" id="linkedin"></a>
                <a href="https://www.instagram.com/syahputra_adha/"><img src="{% static 'images/Instagram.png' %}" alt="" id="instagram"></a>
            </div>
            <div class="kanan">
                <a href="404"><img src="{% static 'images/Mail.png' %}" alt="" id="mail"></a>
            </div>
        </div>
            <p id="copyright">
                Copyright © 2020 by Muhamad Akbar Syahputra Adha, all rights reserved
            </p>
    </div>
</body>
</html>

templates/base1page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

    {% block title %}
    {% endblock %}

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light" id="navbar">
        <div id="nav-kiri">
            <img src="{% static 'images/Group 3.png' %}" alt="orang_ganteng" width="60px" height="60px">
            <p>Muhamad Akbar Syahputra Adha</p>
        </div>

        <div id="nav-kanan">
            <ul class="nav">
                <li class="nav-item">
                    <a class="nav-link" href="home">Home</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="#!">Story PPW <img src="{% static 'images/drop-down-arrow.png' %}" alt="dropdown arrow" width="10px" height="10px"></a>

                    <div class="dropdown-content">
                        <a href="/story1">Story 1</a>
                        <a href="/story5">Story5</a>
                        <a href="/story6">Story 6</a>
                        <a href="{% url 'story7:home7' %}">Story 7</a>
                        <a href="{% url 'story8:home8b' %}">Story 8</a>
                        <a href="{% url 'story9:home9' %}">Story 9</a>
                        <a href="/coming-soon">Coming Soon</a>
                    </div>
                </li>
              </ul>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

    <div class="footer1page">
        <div class="sosmed">
            <div class="kiri">
                <a href="home"><img src="{% static 'images/home.png' %}" alt="" id="home"></a>
            </div>
            <div class="tengah">
                <a href="https://www.youtube.com/channel/UCmxW3Ywk5kM4k9vPuPBffLg"><img src="{% static 'images/Youtube.png' %}" alt="" id="youtube"></a>
                <a href="https://www.linkedin.com/in/muhamad-akbar-syahputra-adha-99b3b9175/"><img src="{% static 'images/LinkedIN.png' %}" alt="" id="linkedin"></a>
                <a href="https://www.instagram.com/syahputra_adha/"><img src="{% static 'images/Instagram.png' %}" alt="" id="instagram"></a>
            </div>
            <div class="kanan">
                <a href="404"><img src="{% static 'images/Mail.png' %}" alt="" id="mail"></a>
            </div>
        </div>
            <p id="copyright">
                Copyright © 2020 by Muhamad Akbar Syahputra Adha, all rights reserved
            </p>
    </div>
    
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.3/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.3/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</body>
</html>

templates/form_kegiatan.html
<!DOCTYPE html>
{% extends 'base1page.html' %}
{% load static %}
<html lang="en">
<head>
    {% block title %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tambah Kegiatan</title>

    <link rel="icon" href="{% static 'images/Group 3.png' %}" type="image/icon type">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'CSS/style.css' %}">

    <link href="https://fonts.googleapis.com/css2?family=Rubik" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
    {% endblock %}
</head>

<body>
    {% block content %}
    <br><br>
    <div class="container" style="color: white;">
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                {{kegiatanForm.nama_kegiatan.label_tag}}
                {{kegiatanForm.nama_kegiatan}}
            </div>

            <button type="Submit" class="btn btn-light" href="list-kegiatan">Selesai</button>
        </form>

        <a href="story6"><button class="btn btn-primary" href="story6">Kembali</button></a>
    </div>
    {% endblock %}

</body>
</html>

templates/form_matkul.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    {% block title %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tambah Matkul</title>

    <link rel="icon" href="{% static 'images/Group 3.png' %}" type="image/icon type">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'CSS/style.css' %}">

    <link href="https://fonts.googleapis.com/css2?family=Rubik" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
    {% endblock %}
</head>

<body>
    {% block content %}
    <br><br>
    <div class="container" style="color: white;">
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                {{matkul_form.nama_matkul.label_tag}}
                {{matkul_form.nama_matkul}}
            </div>

            <div class="form-group">
                {{matkul_form.dosen_pengajar.label_tag}}
                {{matkul_form.dosen_pengajar}}
            </div>

            <div class="form-group">
                {{matkul_form.ruang_matkul.label_tag}}
                {{matkul_form.ruang_matkul}}
            </div>

            <div class="form-group">
                {{matkul_form.jumlah_sks.label_tag}}<br>
                {{matkul_form.jumlah_sks}}
            </div>

            <div class="form-group">
                {{matkul_form.deskripsi_matkul.label_tag}}<br>
                {{matkul_form.deskripsi_matkul}}
            </div>

            <div class="form-group">
                {{matkul_form.semester_tahun.label_tag}}<br>
                {{matkul_form.semester_tahun}}
            </div>

            <button type="Submit" class="btn btn-light" href="list-matkul">Selesai</button>
        </form>

        <a href="story5"><button class="btn btn-primary" href="story5">Kembali</button></a>
    </div>
    {% endblock %}

</body>
</html>

templates/form_peserta.html
<!DOCTYPE html>
{% extends 'base1page.html' %}
{% load static %}
<html lang="en">
<head>
    {% block title %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tambah Peserta</title>

    <link rel="icon" href="{% static 'images/Group 3.png' %}" type="image/icon type">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'CSS/style.css' %}">

    <link href="https://fonts.googleapis.com/css2?family=Rubik" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
    {% endblock %}
</head>

<body>
    {% block content %}
    <br><br>
    <div class="container" style="color: white;">
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                {{pesertaForm.nama_peserta.label_tag}}
                {{pesertaForm.nama_peserta}}
            </div>

            <button type="Submit" class="btn btn-light" href="list-kegiatan">Selesai</button>
        </form>

        <a href="story6"><button class="btn btn-primary" href="story6">Kembali</button></a>
    </div>
    {% endblock %}

</body>
</html>

templates/list_kegiatan.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    {% block title %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Daftar Matkul</title>

    <link rel="icon" href="{% static 'images/Group 3.png' %}" type="image/icon type">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'CSS/style.css' %}">

    <link href="https://fonts.googleapis.com/css2?family=Rubik" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
    {% endblock %}
</head>

<body>
    {% block content %}

    <div class="container" style="min-height: 400px;">
        <br><br>
        <div class="kotak-biru" style="color: white;">
            <h1>Daftar Kegiatan</h1>
        </div>
        <br><br>

        {% for i in Kegiatan %}
        <div class="card-deck" style="background-color: #3282B8;">
          <div class="card" style="background-color: #bbe1fa;">
            <div class="kontener" style="display: flex; justify-content:space-between;">
              <div class="card-body col-lg-6">
                <h4 class="card-title">{{i.nama_kegiatan}}</h4>
                {% for j in Peserta %}
                  {% if j.kegiatan == i %}
                    <p class="card-text">- {{j.nama_peserta}}</p>
                    <a href="delete-peserta/{{j.id}}" class="card-link"> <button type="button" class="btn btn-danger">Hapus</button></a>
                  {% endif %}
                {% endfor %}
              </div>
              <div class="col-lg-6">
                <br>
                <div class="row">
                  <div class="col-lg-4"></div>
                  <div class="col-lg-2">
                    <a href="delete-kegiatan/{{i.id}}" class="card-link"> <button type="button" class="btn btn-danger">Hapus</button></a>
                  </div>
                  <div class="col-lg-2">
                    <a href="tambah-peserta/{{i.id}}" class="card-link"> <button type="button" class="btn btn-info">Tambah</button></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <br>
      {% endfor %}
      <div class="container" style="text-align: center;">
        <a href="/story6" class="card-link"> <button type="button" class="btn btn-primary">Kembali</button></a>
      </div>
    </div>

    {% endblock %}
</body>
</html>